### ISSUE TITLE
Growth chart: crash on missing quantity measurement unit code

### ISSUE THREAD

**Issue by michelemottini** [smart-on-fhir/apps-old#3]
The growth chart app crashes if the weight/height/bmi quantities returned by the FHIR server specify "units" but not "code"

**Comment by nschwertner** [comment]
It looks like this is due to this code in the FHIR JS client which assumes that `code` is available in `valueQuantity`:
https://github.com/smart-on-fhir/client-js/blob/master/client/utils.js#L41

For SMART on FHIR profiles `code` is expected in the units of measurement coding.

**Comment by jmandel** [comment]
Please note that in the FHIR "Quantity" data type, "units" represents a
human-readable description, and "code" is used for the machine-readable
ucum code. So for automated processing, "code" is the correct field.

That said, of course the app should gracefully handle a missing unit,
rather than crashing :-)

Hope this helps!

**Comment by michelemottini** [comment]
(

...growth chart app logging in and getting data from out HIE platform:

![image](https://cloud.githubusercontent.com/assets/1046280/5769758/f81161ec-9ced-11e4-91d3-74317b71277d.png)

)

**Comment by michelemottini** [comment]
> [The units](http://www.hl7.org/implement/standards/fhir/datatypes.html#Quantity) element contains a displayable unit that defines what is measured. The units _may additionally_ be coded in some formal way using the code and the system

**Comment by jmandel** [comment]
Totally, yes: the "units" value _may be_ coded. But the "code" value _is_
by definition coded (see
http://www.hl7.org/implement/standards/fhir/datatypes-definitions.html#Quantity.code),
and with the further requirement that ucum be used whenever possible. This
is why we use "code" as the source of truth. Hope this helps!

**Comment by nschwertner** [comment]
Very nice work, Michele. Glad to see the app in action at your site.
