### ISSUE TITLE
Implement need_patient_banner in the growth chart app

### ISSUE THREAD

**Issue by michelemottini** [smart-on-fhir/apps-old#4]
It would be nice if `need_patient_banner=false` removed the patient data at the top of the app, to save screen space and avoid duplicate data when running embedded:

![image](https://cloud.githubusercontent.com/assets/1046280/6240034/d684371c-b6d7-11e4-837d-e16169066cbd.png)

**Comment by nschwertner** [comment]
You can hide the patient header by tweaking this in-app setting:
https://github.com/smart-on-fhir/apps/blob/master/static/apps/growth-chart/js/gc-chart-config.js#L66

I will look into the current state of the need_patient_banner setting handling in the JS client and the growth charts app. Stay tuned

**Comment by michelemottini** [comment]
Got it, thanks

**Comment by nschwertner** [comment]
Fixed in https://github.com/smart-on-fhir/apps/commit/a635f2489386ffb4619604ea260d8420d4f333e4

Also, the SMART reference sandbox now injects need_patient_banner in the app's context

**Comment by michelemottini** [comment]
Cool, thanks!

This is not yet at fhir.smartplatforms.org/apps/growth-chart, correct?

**Comment by nschwertner** [comment]
Should be. Perhaps purging  the browser cache will help

**Comment by jmandel** [comment]
Quick question: [this change](https://github.com/smart-on-fhir/apps/commit/a635f2489386ffb4619604ea260d8420d4f333e4#diff-203b64468523bd40ca6660c43117f44cR17) compares the value to the string `"false"` rather than the JS boolean `false`. Is that a bug?

**Comment by michelemottini** [comment]
I was wondering about that  - I just changed our host code to return a
string.

The specs here
http://docs.smartplatforms.org/authorization/scopes-and-launch-context/ do
not specify the type of the launch context parameters

**Comment by michelemottini** [comment]
Works nicely:

![image](https://cloud.githubusercontent.com/assets/1046280/6378393/0416f382-bcf9-11e4-9e21-416fcdf0e0b9.png)

**Comment by jmandel** [comment]
We should clarify the docs, by adding double-quotes around the string-typed examples (and perhaps adding an explicit "type" column). But the intention is to use a boolean for this value. (All the other params we've defined to-date are strings.)

**Comment by jmandel** [comment]
Updated the spec at https://github.com/smart-on-fhir/smart-on-fhir.github.io/commit/034fc9f2022a9392ebf7432d9b1fe3c0e288e16e to indicate types. @nschwertner, can update our code to use a boolean for `needs_patient_banner`?

**Comment by nschwertner** [comment]
ok, changing to boolean

**Comment by michelemottini** [comment]
OK, good - I am reverting my change to go back to boolean

**Comment by nschwertner** [comment]
hmm.... not as straight forward - our stack (API server and Authorization server) assumes that all the key:value pairs in the app context and the authorization token are strings

**Comment by jmandel** [comment]
As long as the app behavior and the spec are right, it's okay if it takes us time to
fix up our reference server. So I'd just go ahead and updates the app for  now. (In the meantime we can simply not return a need_patient_banner
value from our server .)

**Comment by nschwertner** [comment]
Apps updated (on sandbox too):
https://github.com/smart-on-fhir/apps/commit/76a4fc04a038739b771bf3cc8fef3d8f9840fa60

**Comment by michelemottini** [comment]
Got it, thanks
