### ISSUE TITLE
Broken authentication sequence?

### ISSUE THREAD

**Issue by michelemottini** [smart-on-fhir/apps-old#5]
Both the growth chart and the cardiac risk apps stopped working:
![image](https://cloud.githubusercontent.com/assets/1046280/6753059/add68c0a-cee9-11e4-8daf-942618ee3bb9.png)

The 'Not found' details are:
![image](https://cloud.githubusercontent.com/assets/1046280/6753078/d6b72f4e-cee9-11e4-8c1e-6f44a8943362.png)

It appears that instead than redirecting to the authorization page on our servers it tries to go to a (wrong) page on the fhirsmarterhealthit.org site

The metadata call and return seem OK:
![image](https://cloud.githubusercontent.com/assets/1046280/6753097/0a9d1c6a-ceea-11e4-89c9-0560ce0253c6.png)

The response is:

``` JS
{"resourceType":"Conformance",
"publisher":"CareEvolution",
"telecom":[{"system":"email","value":"info@careevolution.com"},{"system":"url","value":"http://careevolution.com"}],
"date":"2015-03-20",
"software":{"name":"HIEBus","version":"0.0.0.0"},
"implementation":{"description":"Base implementation: Patient, Observation (partial), DiagnosticReport (partial)"},
"fhirVersion":"0.0.82",
"acceptUnknown":false,
"format":["xml","json"],
"rest":[{
"mode":"server",
"security":{
"extension":[{"url":"http://fhir-registry.smartplatforms.org/Profile/oauth-uris#authorize","valueUri":"http://localhost/WebClientTest.Adapter1.WebClient/OAuth2/Authorize"},{"url":"http://fhir-registry.smartplatforms.org/Profile/oauth-uris#token","valueUri":"http://localhost/WebClientTest.Adapter1.WebClient/api/OAuth2/Token"}],"cors":true,"service":[{"coding":[{"system":"http://hl7.org/fhir/restful-security-service","code":"OAuth2"}]}]},"resource":[{"type":"Patient","operation":[{"code":"create"},{"code":"delete"},{"code":"read"},{"code":"search-type"},{"code":"update"},{"code":"validate"}],"readHistory":false,"updateCreate":true,"searchParam":[{"name":"_id","type":"token"},{"name":"address","type":"string"},{"name":"birthdate","type":"date"},{"name":"family","type":"string"},{"name":"gender","type":"token"},{"name":"given","type":"string"},{"name":"identifier","type":"token"},{"name":"language","type":"token"},{"name":"name","type":"string"},{"name":"telecom","type":"string"}]},{"type":"Observation","operation":[{"code":"read"},{"code":"search-type"}],"readHistory":false,"updateCreate":false,"searchParam":[{"name":"_id","type":"token"},{"name":"name","type":"token"},{"name":"subject","type":"reference"}]},{"type":"DiagnosticReport","operation":[{"code":"read"},{"code":"search-type"}],"readHistory":false,"updateCreate":false,"searchParam":[{"name":"_id","type":"token"},{"name":"date","type":"date"},{"name":"subject","type":"reference"}]}]}]}
```

**Comment by nschwertner** [comment]
Sorry about that. You will need to update the JS client that the apps are using.

```
Due to the recent update in our domain our API server's conformance statement and our sample patients data have changed slightly. If you are using one of our official clients (JavaScript and Python) for your SMART app, you will have to update them to the latest version.

For the JavaScript client, you can download the latest version from:
https://raw.githubusercontent.com/smart-on-fhir/client-js/master/dist/fhir-client.js

For the Python client, you can update using PIP:
   pip uninstall fhirclient
   pip install fhirclient

Besides updating the client that you are using, you may also need to update your app's code, if you have dependencies on our FHIR extensions and codes. The easiest way to achieve this is to run a global search and replace in your code as follows:

   Search for:  smartplatforms.org
   Replace with: smarthealthit.org
```

**Comment by nschwertner** [comment]
Please consider following our Google Group which is our primary developers' notification channel at the moment: https://groups.google.com/forum/#!forum/smart-on-fhir

**Comment by nschwertner** [comment]
Actually, let me take that back... You are using our hosted copies of the apps, no? If so, then the problem is the other way around... you will have to update your conformance statement by changing `smartplatforms.org` to `smarthealthit.org`

**Comment by nschwertner** [comment]
In the long run, it may be a good idea to host local copies of the components from the SMART Sandbox that you are using to avoid such dependencies upon our cloudhosted sandbox.

**Comment by michelemottini** [comment]
Ah that makes sense...thanks!

I am subscribing to the Google Group

**Comment by michelemottini** [comment]
> In the long run, it may be a good idea to host local copies of the components from the SMART Sandbox that you are using to avoid such dependencies upon our cloudhosted sandbox.

Our main focus is on developing the FHIR + OAuth server, not the apps - having the hosted apps to test is nice (and it makes for good interoperability demos)

**Comment by michelemottini** [comment]
Changing the URLs in the conformance statement fixed the problem, thanks
