### ISSUE TITLE
Add license documentation

### ISSUE THREAD

**Issue by kpshek** [smart-on-fhir/apps-old#6]
I am not able to find any documentation on the open source license the code in the SMART on FHIR Github organization has been released under. In the US, source code is inherently copyrighted by the authors of the work so if there is not a license specified, it's not legally open source.

Can an open license be specified? I'm assuming the intention here is for this code to be open source based on past offline discussions and comments in the documentation like this: ["...the open-source SMART Growth Charts app..."](https://github.com/smart-on-fhir/smart-on-fhir.github.io/blob/80c2a474beadc5444de5c2eeb96ee14328aca2fb/tutorials/index.md)

Thanks! :smile:

**Comment by nschwertner** [comment]
We definitely license under Apache2... I will add license text files to the repositories to make it explicit. Thank you for pointing thins out

**Comment by nschwertner** [comment]
License added

**Comment by kpshek** [comment]
Thanks @nschwertner
